#
# Github Workflow to build & test.
#
name: Build
on: [ push ]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    name: 'Gradle Build'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Set up Java'
        uses: 'actions/setup-java@v2'
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: 'Unlock git-crypt secrets'
        uses: 'sliteteam/github-action-git-crypt-unlock@1.2.0'
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: 'Grant execute permission for gradlew'
        run: 'chmod +x gradlew'
      - name: 'Build with Gradle'
        run: './gradlew build --no-daemon'
      - name: 'Archive artifacts'
        uses: 'actions/upload-artifact@v2'
        with:
          name: 'reports'
          path: 'build/reports'